sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: existence19762

  alioss:
    endpoint: oss-cn-shanghai.aliyuncs.com
    access-key-id: LTAI5tSeNpof2jq9vWV2NAt7
    access-key-secret: PryDoUXke8tYDnkvie5CXyzWmtxjai
    bucket-name: sky-linlin

  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10
